# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import myopica.portfolio.models


class Migration(migrations.Migration):

    replaces = [('portfolio', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('ordinality', models.PositiveSmallIntegerField(default=myopica.portfolio.models.count_galleries)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinality', models.PositiveSmallIntegerField(default=myopica.portfolio.models.count_images)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(editable=False, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('medium', models.CharField(blank=True, max_length=256)),
                ('ahash', models.CharField(default=b'', max_length=256, null=True)),
                ('extension', models.CharField(default=b'.jpg', max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Image'),
        ),
    ]
